new_blog/config/routes.rb
NewBlog::Application.routes.draw do
  get "sitemap/index"
  get "contact/index"
  get "biography/index"
  get "welcome/index"
  resources :blogs

end

new_blog/app/models/blog.rb
class Blog < ActiveRecord::Base
end

new_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

new_blog/app/controllers/biography_controller.rb
class BiographyController < ApplicationController
  def index
  end
end

new_blog/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blog }
      else
        format.html { render action: 'new' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:user_id, :title, :text)
    end
end

new_blog/app/controllers/contact_controller.rb
<head>
</head>
<body>
    <h1>Information<h1>
    <p>
    <a href="http://mensweardog.tumblr.com/">mensweardog.tumblr.com</a>
    <a href="http://www.reformationproject.org/">The Reformation Project</a>
    <a href="http://www.indochino.com/">Indochino</a>
    <input type="email" placeholder="Your email">
    <input type="submit">
</body>

new_blog/app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
  end
end

new_blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

new_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

new_blog/app/helpers/biography_helper.rb
module BiographyHelper
end

new_blog/app/helpers/blogs_helper.rb
module BlogsHelper
end

new_blog/app/helpers/contact_helper.rb
module ContactHelper
end

new_blog/app/helpers/sitemap_helper.rb
module SitemapHelper
end

new_blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

new_blog/app/views/biography/index.html.erb
<h1>Schedule a Fitting</h1>
<head>
    <style>
        body {
            text-align: center;
            background: white;
            color: white;
            font-family: Helvetica;
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
             }
        p  {
            text-align: center;
            font-size: 44;
            color: black;
        }
        input {
            border: 0;
            padding: 12px;
            font-size: 18px;
        }
        input[type="submit"]{
            background: purple;
            color: black;
        }
    </style>
</head>
<body>
    <iframe src="//instagram.com/p/iHqd8fAW5o/embed/" width="612" height="710" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
    <p>megrhinehart@gmail.com 
    <br>
    <a href="http://techtalentsouth.com">Tech Talent South</a>
</p>

</body>

new_blog/app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

new_blog/app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

new_blog/app/views/blogs/index.html.erb
<h1>Megan's Blog!!!</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.user_id %></td>
        <td><%= blog.title %></td>
        <td><%= blog.text %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

new_blog/app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

new_blog/app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @blog.text %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

new_blog/app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

new_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

new_blog/app/views/sitemap/index.html.erb
<!DOCTYPE html>
<html>
  
<body>

<h1>Zuit Sitemap</h1>
<ul>
  <li><a href="http://0.0.0.0:3000/welcome/index">Homepage</a></li>
  <li><a href="http://zuitco.tumblr.com/">Blog</a></li>
  <li><a href="http://0.0.0.0:3000/biography/index">Biography</a></li>
</ul>
</body>
</html>

new_blog/app/views/welcome/index.html.erb
<!DOCTYPE html>
<head>
    <style>
        body {
            text-align: center;
            background: white;
            color: white;
            font-family: Helvetica;
            background-size: cover;
            background-position: center center;
            background-repeat: no-repeat;
            background-attachment: fixed;
             }
        p  {
            font-size: 34;
        }
        input {
            border: 0;
            padding: 12px;
            font-size: 18px;
        }
        input[type="submit"]{
            background: purple;
            color: white;
        }
        li
        {
        font-family: garamond;
        font-size: 24px;
        display:inline;
        width: 60px;
        text-decoration:none;
        list-style: none;
        width:100px;
        margin:20px;
        padding:5px 0;
        }
    </style>
</head>

<body>
    <h1>
    <a href="http://stackoverflow.com">
    <img src="http://farm8.staticflickr.com/7326/12208207714_e598b742d0_o.png"/>
    </a>
    </h1>
    <ul>
        <li><a href="#home">Catalog</a></li>
        <li><a href="#news">Custom</a></li>
        <li><a href="http://zuitco.tumblr.com/">Blog</a></li>
        <li><a href="#about">Launch</a></li>
    </ul>
    <img src="http://farm8.staticflickr.com/7440/12207850203_566c286336_b.jpg">
    <p>Email subscribe, schedule a fitting, link to our facebook, catalog<br> Super 140s wool, bemberg lining and personalized monogramming</p>
    <input type="email" placeholder="Your email">
    <input type="submit">
</body>